### ISSUE TITLE
Report for Regression Task

### ISSUE THREAD

**Issue by bvancea** [bvancea/ml-project-13#3]
We need to write this fast I guess :watch: 

Am inceput pe [sharelatex](https://www.sharelatex.com/project/527121d356f405b171002be6?r=b1d93a67&rs=ps&rm=d) . Jump in if you have time

**Comment by bvancea** [comment]
First draft done :cool:

Monica, nu iti stiu mail-ul de eth :)

**Comment by monicadragan** [comment]
Poti vedea si in istoric - in mare am facut urmatoarele mici modificari:
- Hinge functions - pune indice la xi: "and $B_i$ represent Hinge functions of the form $max(0,x_i-c)$ or $max(x_i-c,0)$."
- Features: "and the _vector of labels_ y"
- ridge regression: "We tried _several polynomial degrees_ and several values of alpha"
  -lasso: using the $L_1$ norm

Super good job!!

Cheers,
Monica
